- name: Ensure .ssh directory exists
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'

- name: Copy private SSH key to remote instance
  copy:
    src: ../../ssh-key
    dest: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Copy SSH config to remote instance
  copy:
    src: ~/.ssh/config
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create jenkins directory
  file:
    path: "/home/ubuntu/jenkins"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

