# Tasks file for Jenkins Master on Ubuntu

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - openjdk-17-jdk
      - git
      - curl
      - wget
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update apt cache after adding Jenkins repo
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins uses correct Java path
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_JAVA_CMD='
    line: 'JENKINS_JAVA_CMD="/usr/bin/java"'
    create: yes
  notify: reload systemd

- name: Enable and start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
